name: Analyze Exports

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  analyze-exports:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important: fetch full history for comparison

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Analyze TypeScript Exports 2
        uses: sergiocarracedo/ts-export-info-action@v1.0.3
        with:
          path: |
            packages/react/src/f0.ts
            packages/react/src/experimental.ts            
          detailed: true  # Set to true for detailed export list
          compare: true # Set to true to compare agains base
          list-changes: true # Set to true list the changes (needs compare true)
          github-token: ${{ secrets.GITHUB_TOKEN }}
